print("Hello World!")
print("Greetings, Program!")
print(1 + 2)
print(7 * 6)
print()
print("escape punctuations in git commit messages")
print("Find REPL for Python3 in Sublime3")
print("Parenthesis" + "ConCat")